"""
analyzers/mitre_mapper.py
Maps security findings to MITRE ATT&CK framework techniques.
Generates ATT&CK Navigator compatible JSON layers.
"""
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

MAPPINGS_FILE = Path(__file__).parent.parent / "config" / "mitre_mappings.json"


class MitreMapper:
    """Maps alerts and findings to MITRE ATT&CK techniques."""

    def __init__(self) -> None:
        self._mappings: Dict[str, Dict] = self._load_mappings()

    def _load_mappings(self) -> Dict[str, Dict]:
        if MAPPINGS_FILE.exists():
            try:
                with open(MAPPINGS_FILE) as fh:
                    return json.load(fh)
            except (json.JSONDecodeError, IOError) as exc:
                log.warning(f"Failed to load MITRE mappings: {exc}")
        return {}

    def get_technique(self, technique_id: str) -> Optional[Dict[str, Any]]:
        """Look up technique details by ID (e.g., 'T1059.001')."""
        return self._mappings.get(technique_id)

    def map_finding(self, finding: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Map a finding to a MITRE technique via trigger or explicit technique_id."""
        # Direct technique ID
        technique_id = finding.get("mitre_technique", "")
        if technique_id and technique_id in self._mappings:
            return self._mappings[technique_id]

        # Try detection trigger mapping
        source_module = finding.get("source_module", "")
        for technique_data in self._mappings.values():
            trigger = technique_data.get("detection_trigger", "")
            if trigger and source_module and trigger in source_module:
                return technique_data

        return None

    def generate_navigator_layer(self, alerts: List[Any]) -> Dict[str, Any]:
        """
        Generate ATT&CK Navigator JSON layer from alerts.
        Compatible with https://mitre-attack.github.io/attack-navigator/
        """
        technique_scores: Dict[str, Dict] = {}

        for alert in alerts:
            technique_id = getattr(alert, "mitre_technique", "") or (
                alert.get("mitre_technique", "") if isinstance(alert, dict) else ""
            )
            if not technique_id:
                continue

            severity = getattr(alert, "severity", "") or (
                alert.get("severity", "Medium") if isinstance(alert, dict) else "Medium"
            )
            score_map = {"Critical": 4, "High": 3, "Medium": 2, "Low": 1}
            score = score_map.get(severity, 1)

            if technique_id not in technique_scores:
                tech_info = self._mappings.get(technique_id, {})
                technique_scores[technique_id] = {
                    "techniqueID": technique_id,
                    "score": score,
                    "color": "",
                    "comment": tech_info.get("technique_name", ""),
                    "enabled": True,
                    "metadata": [],
                    "showSubtechniques": False,
                    "tactic": tech_info.get("tactic", ""),
                }
            else:
                technique_scores[technique_id]["score"] = min(
                    4, technique_scores[technique_id]["score"] + 1
                )

        # Color by score
        color_map = {1: "#5bc0de", 2: "#f0ad4e", 3: "#d9534f", 4: "#c0392b"}
        for tech in technique_scores.values():
            tech["color"] = color_map.get(tech["score"], "#5bc0de")

        return {
            "name": "BlueSentinel v2.0 Detection Layer",
            "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
            "domain": "enterprise-attack",
            "description": "Auto-generated by BlueSentinel v2.0",
            "filters": {"platforms": ["Windows"]},
            "sorting": 3,
            "layout": {"layout": "side", "aggregateFunction": "max", "showID": True, "showName": True},
            "hideDisabled": False,
            "techniques": list(technique_scores.values()),
            "gradient": {
                "colors": ["#ffffff", "#ff6666"],
                "minValue": 0,
                "maxValue": 4,
            },
            "legendItems": [
                {"label": "Low", "color": "#5bc0de"},
                {"label": "Medium", "color": "#f0ad4e"},
                {"label": "High", "color": "#d9534f"},
                {"label": "Critical", "color": "#c0392b"},
            ],
            "metadata": [],
            "links": [],
            "showTacticRowBackground": True,
            "tacticRowBackground": "#0a0e1a",
            "selectTechniquesAcrossTactics": True,
            "selectSubtechniquesWithParent": False,
            "selectVisibleTechniques": False,
        }
